// <auto-generated />
using System;
using CrowsWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrowsWebsite.Migrations
{
    [DbContext(typeof(websiteContext))]
    [Migration("20200601103638_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrowsWebsite.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberId1")
                        .HasColumnType("int");

                    b.Property<string>("img_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("max_players")
                        .HasColumnType("int");

                    b.Property<int>("max_playtime")
                        .HasColumnType("int");

                    b.Property<int>("min_players")
                        .HasColumnType("int");

                    b.Property<int>("min_playtime")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rules_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberId1");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CrowsWebsite.Models.GamingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfSession")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GamingSessions");
                });

            modelBuilder.Entity("CrowsWebsite.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GamingSessionId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GamingSessionId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CrowsWebsite.Models.Game", b =>
                {
                    b.HasOne("CrowsWebsite.Models.Member", null)
                        .WithMany("LikeToPlayGames")
                        .HasForeignKey("MemberId");

                    b.HasOne("CrowsWebsite.Models.Member", null)
                        .WithMany("ownedGames")
                        .HasForeignKey("MemberId1");
                });

            modelBuilder.Entity("CrowsWebsite.Models.Member", b =>
                {
                    b.HasOne("CrowsWebsite.Models.GamingSession", null)
                        .WithMany("Atendees")
                        .HasForeignKey("GamingSessionId");
                });
#pragma warning restore 612, 618
        }
    }
}
